select
    assignment_id,
    order_id,
    box_id,
    rfid_tag,
    box_type,
    box_capacity,
    sequence_number,
    subsequence,
    lifecycle_phase,
    sla_status,
    assigned_at,
    dispatched_at,
    delivered_at,
    picked_up_at,
    returned_at,
    return_condition,
    turnaround_hours,
    dispatch_lag_minutes,
    dwell_hours,
    days_since_assigned,
    is_returned,
    cast(assigned_at as date)   as assignment_date
from {{ ref('int_box_lifecycle') }}
